version: "3.1"

services:
  db:
    container_name: mysql
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: teste
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: teste
    volumes:
      - db:/var/lib/mysql
    networks:
      - mysql-network

volumes:
  db:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: 'C:\docker_sharing'

networks:
  mysql-network:
    driver: bridge
